// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lcoqwtridqxvhoaenlxq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxjb3F3dHJpZHF4dmhvYWVubHhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0OTk3ODcsImV4cCI6MjA2NDA3NTc4N30.Sx7mNtXTym-KOGmzcnHGxltzYrDWOoUX0t7re-pHfS0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);